### PR TITLE
Update to Bot API 7.2

### LINKED ISSUE #278: editMessageReplyMarkup will always throw for default values
https://github.com/reo7sp/tgbot-cpp/blob/9343618bdea96942c86fa8fc927a28f2885550af/src/Api.cpp#L1894

If the value is `0`, `get<string>` will throw, if the value is `""`, `get<int>` will throw

### PR DESCRIPTION
**Pull request by llnulldisk**
Added support for the Telegram Bot API 6.6 with the following changes:
- Added the ability to set different bot descriptions for different user languages using the method [setMyDescription](https://core.telegram.org/bots/api#setmydescription).
- Added the ability to get the current bot description in the given language as the class [BotDescription](https://core.telegram.org/bots/api#botdescription) using the method [getMyDescription](https://core.telegram.org/bots/api#getmydescription).
- Added the ability to set different bot short descriptions for different user languages using the method [setMyShortDescription](https://core.telegram.org/bots/api#setmyshortdescription).
- Added the ability to get the current bot short description in the given language as the class [BotShortDescription](https://core.telegram.org/bots/api#botshortdescription) using the method [getMyShortDescription](https://core.telegram.org/bots/api#getmyshortdescription).
- Added the parameter emoji to the method [sendSticker](https://core.telegram.org/bots/api#sendsticker) to specify an emoji for just uploaded stickers.
- Added support for the creation of custom emoji sticker sets in [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).
- Added the parameter needsRepainting to the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset) to automatically change the color of emoji based on context (e.g., use text color in messages, accent color in statuses, etc.).
- Added the field needsRepainting to the class [Sticker](https://core.telegram.org/bots/api#sticker).
- Replaced the parameters pngSticker, tgsSticker, webmSticker, emojis and maskPosition in the method [addStickerToSet](https://core.telegram.org/bots/api#addstickertoset) with the parameter sticker of the type [InputSticker](https://core.telegram.org/bots/api#inputsticker).
- Added support for the creation of sticker sets with multiple initial stickers in [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset) by replacing the parameters pngSticker, tgsSticker, webmSticker, emojis and maskPosition with the parameters stickers and stickerFormat.
- Added support for .WEBP files in [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset) and [addStickerToSet](https://core.telegram.org/bots/api#addstickertoset).
- Added support for .WEBP, .TGS, and .WEBM files in [uploadStickerFile](https://core.telegram.org/bots/api#uploadstickerfile) by replacing the parameter pngSticker in the method [uploadStickerFile](https://core.telegram.org/bots/api#uploadstickerfile) with the parameters sticker and stickerFormat.
- Added the method [setCustomEmojiStickerSetThumbnail](https://core.telegram.org/bots/api#setcustomemojistickersetthumbnail) for editing the thumbnail of custom emoji sticker sets created by the bot.
- Added the method [setStickerSetTitle](https://core.telegram.org/bots/api#setstickersettitle) for editing the title of sticker sets created by the bot.
- Added the method [deleteStickerSet](https://core.telegram.org/bots/api#deletestickerset) for complete deletion of a given sticker set that was created by the bot.
- Added the method [setStickerEmojiList](https://core.telegram.org/bots/api#setstickeremojilist) for changing the list of emoji associated with a sticker.
- Added the method [setStickerKeywords](https://core.telegram.org/bots/api#setstickerkeywords) for changing the search keywords assigned to a sticker.
- Added the method [setStickerMaskPosition](https://core.telegram.org/bots/api#setstickermaskposition) for changing the [mask position](https://core.telegram.org/bots/api#maskposition) of a mask sticker.
- Renamed the field thumb in the classes [Animation](https://core.telegram.org/bots/api#animation), [Audio](https://core.telegram.org/bots/api#audio), [Document](https://core.telegram.org/bots/api#document), [Sticker](https://core.telegram.org/bots/api#sticker), [Video](https://core.telegram.org/bots/api#video), [VideoNote](https://core.telegram.org/bots/api#videonote), [InputMediaAnimation](https://core.telegram.org/bots/api#inputmediaanimation), [InputMediaAudio](https://core.telegram.org/bots/api#inputmediaaudio), [InputMediaDocument](https://core.telegram.org/bots/api#inputmediadocument), [InputMediaVideo](https://core.telegram.org/bots/api#inputmediavideo), [StickerSet](https://core.telegram.org/bots/api#stickerset) to thumbnail.
- Renamed the parameter thumb in the methods [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote) to thumbnail.
- Renamed the method setStickerSetThumb to [setStickerSetThumbnail](https://core.telegram.org/bots/api#setstickersetthumbnail) and its parameter thumb to thumbnail.
- Renamed the fields thumbUrl, thumbWidth, and thumbHeight in the classes [InlineQueryResultArticle](https://core.telegram.org/bots/api#inlinequeryresultarticle), [InlineQueryResultContact](https://core.telegram.org/bots/api#inlinequeryresultcontact), [InlineQueryResultDocument](https://core.telegram.org/bots/api#inlinequeryresultdocument), [InlineQueryResultLocation](https://core.telegram.org/bots/api#inlinequeryresultlocation), and [InlineQueryResultVenue](https://core.telegram.org/bots/api#inlinequeryresultvenue) to thumbnailUrl, thumbnailWidth, and thumbnailHeight respectively.
- Renamed the field thumbUrl in the classes [InlineQueryResultPhoto](https://core.telegram.org/bots/api#inlinequeryresultphoto) and [InlineQueryResultVideo](https://core.telegram.org/bots/api#inlinequeryresultvideo) to thumbnailUrl.
- Renamed the fields thumbUrl and thumbMimeType in the classes [InlineQueryResultGif](https://core.telegram.org/bots/api#inlinequeryresultgif), and [InlineQueryResultMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultmpeg4gif) to thumbnailUrl and thumbnailMimeType respectively.

Added support for the Telegram Bot API 6.7 with the following changes:
- Added support for launching [Web Apps](https://core.telegram.org/bots/webapps) from inline query results by replacing the parameters switchPmText and switchPmParameter of the method [answerInlineQuery](https://core.telegram.org/bots/api#answerinlinequery) with the parameter button of type [InlineQueryResultsButton](https://core.telegram.org/bots/api#inlinequeryresultsbutton).
- Added the field webAppName to the class [WriteAccessAllowed](https://core.telegram.org/bots/api#writeaccessallowed).
- Added the field switchInlineQueryChosenChat of the type [SwitchInlineQueryChosenChat](https://core.telegram.org/bots/api#switchinlinequerychosenchat) to the class [InlineKeyboardButton](https://core.telegram.org/bots/api#inlinekeyboardbutton), which allows bots to switch to inline mode in a chosen chat of the given type.
- Added the field viaChatFolderInviteLink to the class [ChatMemberUpdated](https://core.telegram.org/bots/api#chatmemberupdated).
- Added the ability to set different bot names for different user languages using the method [setMyName](https://core.telegram.org/bots/api#setmyname).
- Added the ability to get the current bot name in the given language as the class [BotName](https://core.telegram.org/bots/api#botname) using the method [getMyName](https://core.telegram.org/bots/api#getmyname).

Added support for the Telegram Bot API 6.8 with the following changes:
- Added the field story to the class [Message](https://core.telegram.org/bots/api#message) for messages with forwarded stories. Currently, it holds no information.
- Added the field voterChat to the class [PollAnswer](https://core.telegram.org/bots/api#pollanswer), to contain channel chat voters in [Polls](https://core.telegram.org/bots/api#poll). For backward compatibility, the field user in such objects will contain the user 136817688 ([@Channel_Bot](https://t.me/Channel_Bot)).
- Added the field emojiStatusExpirationDate to the class [Chat](https://core.telegram.org/bots/api#chat).
- Added the method [unpinAllGeneralForumTopicMessages](https://core.telegram.org/bots/api#unpinallgeneralforumtopicmessages).

Added support for the Telegram Bot API 6.9 with the following changes:
- Added the new administrator privileges canPostStories, canEditStories and canDeleteStories to the classes [ChatMemberAdministrator](https://core.telegram.org/bots/api#chatmemberadministrator) and [ChatAdministratorRights](https://core.telegram.org/bots/api#chatadministratorrights).
- Added the parameters canPostStories, canEditStories and canDeleteStories to the method [promoteChatMember](https://core.telegram.org/bots/api#promotechatmember). Currently, bots have no use for these privileges besides assigning them to other administrators.
- Added the ability to set any header color for Web App using the method setHeaderColor.
- Added Web App events writeAccessRequested and contactRequested.
- Added the fields fromRequest and fromAttachmentMenu to the class [WriteAccessAllowed](https://core.telegram.org/bots/api#writeaccessallowed).

Added support for the Telegram Bot API 7.0 with the following changes:
- Reactions
    - Added the classes [ReactionTypeEmoji](https://core.telegram.org/bots/api#reactiontypeemoji) and [ReactionTypeCustomEmoji](https://core.telegram.org/bots/api#reactiontypecustomemoji) representing different types of reaction.
    - Added updates about a reaction change on a message with non-anonymous reactions, represented by the class [MessageReactionUpdated](https://core.telegram.org/bots/api#messagereactionupdated) and the field messageReaction in the class [Update](https://core.telegram.org/bots/api#update). The bot must explicitly allow the update to receive it.
    - Added updates about reaction changes on a message with anonymous reactions, represented by the class [MessageReactionCountUpdated](https://core.telegram.org/bots/api#messagereactioncountupdated) and the field messageReactionCount in the class [Update](https://core.telegram.org/bots/api#update). The bot must explicitly allow the update to receive it.
    - Added the method [setMessageReaction](https://core.telegram.org/bots/api#setmessagereaction) that allows bots to react to messages.
    - Added the field availableReactions to the class [Chat](https://core.telegram.org/bots/api#chat).

- Replies 2.0
    - Added the class [ExternalReplyInfo](https://core.telegram.org/bots/api#externalreplyinfo) and the field externalReply of type [ExternalReplyInfo](https://core.telegram.org/bots/api#externalreplyinfo) to the class [Message](https://core.telegram.org/bots/api#message), containing information about a message that is replied to by the current message, but can be from another chat or forum topic.
    - Added the class [TextQuote](https://core.telegram.org/bots/api#textquote) and the field quote of type [TextQuote](https://core.telegram.org/bots/api#textquote) to the class Message, which contains the part of the replied message text or caption that is quoted in the current message.
    - <ins>**Added the class [ReplyParameters](https://core.telegram.org/bots/api#replyparameters) and replaced parameters replyToMessageId and allowSendingWithoutReply in the methods [copyMessage](https://core.telegram.org/bots/api#copymessage), [sendMessage](https://core.telegram.org/bots/api#sendmessage), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendSticker](https://core.telegram.org/bots/api#sendsticker), [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote), [sendVoice](https://core.telegram.org/bots/api#sendvoice), [sendLocation](https://core.telegram.org/bots/api#sendlocation), [sendVenue](https://core.telegram.org/bots/api#sendvenue), [sendContact](https://core.telegram.org/bots/api#sendcontact), [sendPoll](https://core.telegram.org/bots/api#sendpoll), [sendDice](https://core.telegram.org/bots/api#senddice), [sendInvoice](https://core.telegram.org/bots/api#sendinvoice), [sendGame](https://core.telegram.org/bots/api#sendgame), and [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup) with the field replyParameters of type [ReplyParameters](https://core.telegram.org/bots/api#replyparameters).**</ins>

- Link Preview Customization
    - Added the class [LinkPreviewOptions](https://core.telegram.org/bots/api#linkpreviewoptions) and replaced the parameter disableWebPagePreview with linkPreviewOptions in the methods [sendMessage](https://core.telegram.org/bots/api#sendmessage) and [editMessageText](https://core.telegram.org/bots/api#editmessagetext).
    - Replaced the field disableWebPagePreview with linkPreviewOptions in the class [InputTextMessageContent](https://core.telegram.org/bots/api#inputtextmessagecontent).
    - Added the field linkPreviewOptions to the class [Message](https://core.telegram.org/bots/api#message) with information about the link preview options used to send the message.

- Multiple Message Actions
    - Added the method [deleteMessages](https://core.telegram.org/bots/api#deletemessages) to allow the deletion of multiple messages in a single request.
    - Added the method [forwardMessages](https://core.telegram.org/bots/api#forwardmessages) for forwarding of multiple messages in a single request.
    - Added the method [copyMessages](https://core.telegram.org/bots/api#copymessages) for copying of multiple messages in a single request.

- Request for multiple users
    - Renamed the class KeyboardButtonRequestUser to [KeyboardButtonRequestUsers](https://core.telegram.org/bots/api#keyboardbuttonrequestusers) and added the field maxQuantity to it.
    - Renamed the field requestUser in the class [KeyboardButton](https://core.telegram.org/bots/api#keyboardbutton) to requestUsers. The old name will still work for backward compatibility.
    - Added the class [UsersShared](https://core.telegram.org/bots/api#usersshared).
    - Replaced the field userShared in the class [Message](https://core.telegram.org/bots/api#message) with the field usersShared.

- Chat Boost
    - Added updates about chat boost changes, represented by the classes [ChatBoostUpdated](https://core.telegram.org/bots/api#chatboostupdated) and [ChatBoostRemoved](https://core.telegram.org/bots/api#chatboostremoved) and the fields chatBoost and removedChatBoost in the class [Update](https://core.telegram.org/bots/api#update). The bot must be an administrator in the chat to receive these updates.
    - Added the classes [ChatBoostSourcePremium](https://core.telegram.org/bots/api#chatboostsourcepremium), [ChatBoostSourceGiftCode](https://core.telegram.org/bots/api#chatboostsourcegiftcode) and [ChatBoostSourceGiveaway](https://core.telegram.org/bots/api#chatboostsourcegiveaway), representing different sources of a chat boost.
    - Added the method [getUserChatBoosts](https://core.telegram.org/bots/api#getuserchatboosts) for obtaining the list of all active boosts a user has contributed to a chat.

- Giveaway
    - Added the class [Giveaway](https://core.telegram.org/bots/api#giveaway) and the field giveaway to the class [Message](https://core.telegram.org/bots/api#message) for messages about scheduled giveaways.
    - Added the class [GiveawayCreated](https://core.telegram.org/bots/api#giveawaycreated) and the field giveawayCreated to the class [Message](https://core.telegram.org/bots/api#message) for service messages about the creation of a scheduled giveaway.
    - Added the class [GiveawayWinners](https://core.telegram.org/bots/api#giveawaywinners) and the field giveawayWinners to the class [Message](https://core.telegram.org/bots/api#message) for messages about the completion of a giveaway with public winners.
    - Added the class [GiveawayCompleted](https://core.telegram.org/bots/api#giveawaycompleted) and the field giveawayCompleted to the class [Message](https://core.telegram.org/bots/api#message) for service messages about the completion of a giveaway without public winners.

- Other Changes
    - Added support for the fields emojiStatusCustomEmojiId and emojiStatusExpirationDate in the class [Chat](https://core.telegram.org/bots/api#chat) for non-private chats.
    - Added the fields accentColorId, backgroundCustomEmojiId, profileAccentColorId, and profileBackgroundCustomEmojiId to the class [Chat](https://core.telegram.org/bots/api#chat).
    - Added the field hasVisibleHistory to the class [Chat](https://core.telegram.org/bots/api#chat).
    - Added the class [MessageOrigin](https://core.telegram.org/bots/api#messageorigin) and replaced the fields forwardFrom, forwardFromChat, forwardFromMessageId, forwardSignature, forwardSenderName, and forwardDate with the field forwardOrigin of type [MessageOrigin](https://core.telegram.org/bots/api#messageorigin) in the class [Message](https://core.telegram.org/bots/api#message).

Added support for the Telegram Bot API 7.1 with the following changes:
 - Added the class [ChatBoostAdded](https://core.telegram.org/bots/api#chatboostadded) and the field boostAdded to the class [Message](https://core.telegram.org/bots/api#message) for service messages about a user boosting a chat.
 - Added the field senderBoostCount to the class [Message](https://core.telegram.org/bots/api#message).
 - Added the field replyToStory to the class [Message](https://core.telegram.org/bots/api#message).
 - Added the fields chat and id to the class [Story](https://core.telegram.org/bots/api#story).
 - Added the field unrestrictBoostCount to the class [Chat](https://core.telegram.org/bots/api#chat).
 - Added the field customEmojiStickerSetName to the class [Chat](https://core.telegram.org/bots/api#chat).

Added support for the Telegram Bot API 7.2 with the following changes:
- Integration with Business Accounts
    - Added the class [BusinessConnection](https://core.telegram.org/bots/api#businessconnection) and updates about the connection or disconnection of the bot to a business account, represented by the field businessConnection in the class [Update](https://core.telegram.org/bots/api#update).
    - Added updates about new messages in a business account connected to the bot, represented by the field businessMessage in the class [Update](https://core.telegram.org/bots/api#update).
    - Added updates about message edits in a business account connected to the bot, represented by the field editedBusinessMessage in the class [Update](https://core.telegram.org/bots/api#update).
    - Added updates about message deletion in a business account connected to the bot, represented by the class [BusinessMessagesDeleted](https://core.telegram.org/bots/api#businessmessagesdeleted) and the field deletedBusinessMessages in the class [Update](https://core.telegram.org/bots/api#update).
    - Added the method [getBusinessConnection](https://core.telegram.org/bots/api#getbusinessconnection).

- Working on Behalf of Business Accounts
    - Added the parameter businessConnectionId to the methods [sendMessage](https://core.telegram.org/bots/api#sendmessage), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendSticker](https://core.telegram.org/bots/api#sendsticker), [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote), [sendVoice](https://core.telegram.org/bots/api#sendvoice), [sendLocation](https://core.telegram.org/bots/api#sendlocation), [sendVenue](https://core.telegram.org/bots/api#sendvenue), [sendContact](https://core.telegram.org/bots/api#sendcontact), [sendPoll](https://core.telegram.org/bots/api#sendpoll), [sendDice](https://core.telegram.org/bots/api#senddice), [sendGame](https://core.telegram.org/bots/api#sendgame), and [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup).
    - Added the parameter businessConnectionId to the method [sendChatAction](https://core.telegram.org/bots/api#sendchataction).
    - Added the field businessConnectionId to the class [Message](https://core.telegram.org/bots/api#message).
    - Added the field senderBusinessBot to the class [Message](https://core.telegram.org/bots/api#message).

- Information about Business Accounts
    - Added the class [BusinessIntro](https://core.telegram.org/bots/api#businessintro) and the field businessIntro to the class [Chat](https://core.telegram.org/bots/api#chat).
    - Added the class [BusinessLocation](https://core.telegram.org/bots/api#businesslocation) and the field businessLocation to the class [Chat](https://core.telegram.org/bots/api#chat).
    - Added the classes [BusinessOpeningHours](https://core.telegram.org/bots/api#businessopeninghours) and [BusinessOpeningHoursInterval](https://core.telegram.org/bots/api#businessopeninghoursinterval) and the field businessOpeningHours to the class [Chat](https://core.telegram.org/bots/api#chat).

- Mixed-Format Sticker Packs
    - Removed the fields isAnimated and isVideo from the class [StickerSet](https://core.telegram.org/bots/api#stickerset).
    - Added the field format to the class [InputSticker](https://core.telegram.org/bots/api#inputsticker).
    - <ins>**Removed the parameter stickerFormat from the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).**</ins>
   -  <ins>**Added the parameter format to the method [setStickerSetThumbnail](https://core.telegram.org/bots/api#setstickersetthumbnail).**</ins>

- Request Chat Improvements
    - Added the fields requestName, requestUsername, and requestPhoto to the class [KeyboardButtonRequestUsers](https://core.telegram.org/bots/api#keyboardbuttonrequestusers).
    - Added the fields requestTitle, requestUsername, and requestPhoto to the class [KeyboardButtonRequestChat](https://core.telegram.org/bots/api#keyboardbuttonrequestchat).
    - Added the class SharedUser and replaced the field userIds in the class [UsersShared](https://core.telegram.org/bots/api#usersshared) with the field users.
    - Added the fields title, username, and photo to the class [ChatShared](https://core.telegram.org/bots/api#chatshared).

- Other Changes
    - Added the field isFromOffline to the class [Message](https://core.telegram.org/bots/api#message).
    - Added the field canConnectToBusiness to the class [User](https://core.telegram.org/bots/api#user).
    - Added the field personalChat to the class [Chat](https://core.telegram.org/bots/api#chat).
    - Added the method [replaceStickerInSet](https://core.telegram.org/bots/api#replacestickerinset),
    - Added the class [Birthdate](https://core.telegram.org/bots/api#birthdate) and the field birthdate to the class [Chat](https://core.telegram.org/bots/api#chat).

Breaking changes are <ins>**marked accordingly**</ins>

Fixed #278 and the same error at 7 other occurrences

### CODE REVIEW

**Comment by llnulldisk** [comment]
Updated the API with the following changes:
- Added support for launching [Web Apps](https://core.telegram.org/bots/webapps) from inline query results by replacing the parameters switchPmText and switchPmParameter of the method [answerInlineQuery](https://core.telegram.org/bots/api#answerinlinequery) with the parameter button of type [InlineQueryResultsButton](https://core.telegram.org/bots/api#inlinequeryresultsbutton).
- Added the field webAppName to the class [WriteAccessAllowed](https://core.telegram.org/bots/api#writeaccessallowed).
- Added the field switchInlineQueryChosenChat of the type [SwitchInlineQueryChosenChat](https://core.telegram.org/bots/api#switchinlinequerychosenchat) to the class [InlineKeyboardButton](https://core.telegram.org/bots/api#inlinekeyboardbutton), which allows bots to switch to inline mode in a chosen chat of the given type.
- Added the field viaChatFolderInviteLink to the class [ChatMemberUpdated](https://core.telegram.org/bots/api#chatmemberupdated).
- Added the ability to set different bot names for different user languages using the method [setMyName](https://core.telegram.org/bots/api#setmyname).
- Added the ability to get the current bot name in the given language as the class [BotName](https://core.telegram.org/bots/api#botname) using the method [getMyName](https://core.telegram.org/bots/api#getmyname).
- Added the ability to change bot settings from the bot's profile in official Telegram apps, including the ability to set animated profile photos.
- Added the ability to specify custom emoji entities using [HTML](https://core.telegram.org/bots/api#html-style) and [MarkdownV2](https://core.telegram.org/bots/api#markdownv2-style) formatting options for bots that purchased additional usernames on [Fragment](https://fragment.com/).

**Review by reo7sp — APPROVED** [review]
Thank you very much!

**Comment by egorpugin** [comment]
@llnulldisk do you generate api changes or write them manually?

**Comment by llnulldisk** [comment]
> @llnulldisk do you generate api changes or write them manually?

Currently I'm still working on a script to generate the changes. With some manual changes I can already generate all the type headers and TgTypeParser. I still write all api methods manually, as they are somewhat more complex.

**Comment by egorpugin** [comment]
@llnulldisk 

You could check out my parser for reference/infos. Generator is also there.
https://github.com/egorpugin/tgbot/tree/master/tools

**Pull request merged**
