### PR TITLE
Implement CurlHttpClient.

### PR DESCRIPTION
**Pull request by egorpugin**

### CODE REVIEW

**Comment by JellyBrick** [comment]
**Nice Job!**

**Comment by egorpugin** [comment]
Ok, seems fine now.

**Comment by JellyBrick** [comment]
HttpClient does not need to throw an exception.

Api.cpp#L1215

**Comment by egorpugin** [comment]
How to return bad result then?

**Comment by JellyBrick** [comment]
@egorpugin All processing is done in `Api`, so `HttpClient` only needs to pass the result.

**Comment by egorpugin** [comment]
Empty result?

**Comment by JellyBrick** [comment]
@egorpugin Api.cpp#L1215 
`throw TgException("tgbot-cpp library can't parse json response. " + string(e.what()));`

**Comment by egorpugin** [comment]
It is not informative.
In my case I get ssl error from curl because of MITM certificate inserted without proxy.
And if we remove those error, I get meaningless "tgbot-cpp library can't parse json response. " with error string from property_tree.

**Comment by egorpugin** [comment]
Ok, I've removed check of http_code, as we still receive valid json answer with error description which is handled by Api.
But curl error means that something fatal happened (ssl failed, logic error - curl request preparation etc.).
TgBot api cannot handle this and we must pass back to user.

**Comment by reo7sp** [comment]
Thanks for the contribution!

I have made some changes before merge:
- Formatted code in some places.
- Splitted one `HttpClient.h` to three files: `HttpClient.h` where only interface resides, `CurlHttpClient.h` where your new http client is and `BoostHttpOnlySslClient.h` where old boost-based http client is.
- &nbsp;
- Created sample with name `echobot-curl-client` where the use of `CurlHttpClient` is shown.
- Also created sample with name `echobot-webhook-server` because example with webhook was somehow forgotten by me.
- Found that webhook server doesn't work and fixed that.
- Found that some older pull-requests commited code with 4 spaces and decided to switch to 4 spaces in all the project because 4 spaces are the default in many style guides nowadays.
- Moved generated doxygen docs to separate gh-pages branch.

**Pull request merged**
